# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Caltech Letters
email:              letters@caltech.edu
description:        "Caltech's science out of the lab and into context"
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://caltechletters.org' # The base hostname & protocol for your site
facebook_username:  caltechletters
twitter_username:   caltechletters
instagram_username: caltechletters
soundcloud_username: caltechletters

markdown:  kramdown
permalink: /:categories/:title
paginate:  50
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - install-git-hooks
  - README.md

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename/
